[package]
name = "rubiks_trainer"
version = "0.1.0"
edition = "2024"

[dependencies]
clearscreen = "4.0.1"
color-eyre = "0.6.5"
crossterm = "0.29.0"
rand = "0.9.1"
ratatui = "0.29.0"
tui-tree-widget = "0.23.1"
